### ISSUE TITLE
Add UI to manage k8s containers, similar to manage containers in docker page.

### ISSUE THREAD

**Issue by sf-jfluckiger** [tableau/bridgectl#1]
The manage docker containers page on the streamlit page:
/Bridge_Containers_-_Manage

Allows users to manage docker containers including remove containers, view metadata about containers, or to view logs. We would like add these same features and use a similar UI, but for bridge containers in K8S.

![image](https://github.com/tableau/bridgectl/assets/108806849/4c47245a-a734-4906-8681-ade034a2c3b0)

**Comment by josephflu** [comment]
This feature has been implemented.
